default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: root
  username: postgres
  port: 5432
  host: db

development:
  <<: *default
  database: test_app_development

  
test:
  <<: *default
  database: test_app_test

production:
  <<: *default
  database: production
  username: test_app
